// <auto-generated />
namespace DataLaayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _1234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1234));
        
        string IMigrationMetadata.Id
        {
            get { return "202111180747223_1234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
